{"row": 1, "error": "NOT NULL constraint failed: companies_branch.company_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_branch.company_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_branch.company_id\n", "fk_logs": [], "data": {"name": "GUDIVADA", "open_date": "2012-01-06", "address1": "None", "phone": "9441563983", "district": "KRISHNA", "raw_csv_data": "{'BranchID': 'S101', 'Branch_Name': 'GUDIVADA', 'Company1': 'SPOORTHI MACTCS LIMITED', 'Company2': 'SPOORTHI MACTCS LIMITED', 'OpenDate': '12/01/06 00:00:00', 'Address1': '', 'Address2': '', 'Phone': ", "company": "None"}}
