{"row": 1, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=48: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "48", "VName": "KOTHAPALLI", "TDate": "None", "raw_csv_data": "{'VCode': '48', 'VName': 'KOTHAPALLI', 'TDate': '06/23/18 00:00:00'}", "branch": "None"}}
{"row": 2, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=49: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "49", "VName": "VISWANADRIPALEM", "TDate": "None", "raw_csv_data": "{'VCode': '49', 'VName': 'VISWANADRIPALEM', 'TDate': '07/21/18 00:00:00'}", "branch": "None"}}
{"row": 3, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=50: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "50", "VName": "GANNAVRAM", "TDate": "2009-02-18", "raw_csv_data": "{'VCode': '50', 'VName': 'GANNAVRAM', 'TDate': '09/02/18 00:00:00'}", "branch": "None"}}
{"row": 4, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=51: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "51", "VName": "THUMMALAPALLI", "TDate": "None", "raw_csv_data": "{'VCode': '51', 'VName': 'THUMMALAPALLI', 'TDate': '04/17/21 00:00:00'}", "branch": "None"}}
{"row": 5, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=52: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "52", "VName": "ANGALURU", "TDate": "2008-02-21", "raw_csv_data": "{'VCode': '52', 'VName': 'ANGALURU', 'TDate': '08/02/21 00:00:00'}", "branch": "None"}}
{"row": 6, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=53: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "53", "VName": "pedaparupudi", "TDate": "2008-05-21", "raw_csv_data": "{'VCode': '53', 'VName': 'pedaparupudi', 'TDate': '08/05/21 00:00:00'}", "branch": "None"}}
{"row": 7, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=54: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "54", "VName": "ANGULURU", "TDate": "2008-09-21", "raw_csv_data": "{'VCode': '54', 'VName': 'ANGULURU', 'TDate': '08/09/21 00:00:00'}", "branch": "None"}}
{"row": 8, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=55: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "55", "VName": "chandrala", "TDate": "2009-12-21", "raw_csv_data": "{'VCode': '55', 'VName': 'chandrala', 'TDate': '09/12/21 00:00:00'}", "branch": "None"}}
{"row": 9, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=56: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "56", "VName": "chandrala", "TDate": "2008-12-21", "raw_csv_data": "{'VCode': '56', 'VName': 'chandrala', 'TDate': '08/12/21 00:00:00'}", "branch": "None"}}
{"row": 10, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=57: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "57", "VName": "MANTADA", "TDate": "None", "raw_csv_data": "{'VCode': '57', 'VName': 'MANTADA', 'TDate': '08/17/21 00:00:00'}", "branch": "None"}}
{"row": 11, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=58: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "58", "VName": "GURIVINDAGUNTA", "TDate": "None", "raw_csv_data": "{'VCode': '58', 'VName': 'GURIVINDAGUNTA', 'TDate': '08/19/21 00:00:00'}", "branch": "None"}}
{"row": 12, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=59: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "59", "VName": "BABUJI PETA (PAMARU)", "TDate": "None", "raw_csv_data": "{'VCode': '59', 'VName': 'BABUJI PETA (PAMARU)', 'TDate': '08/21/21 00:00:00'}", "branch": "None"}}
{"row": 13, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=60: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "60", "VName": "RAMANAPUDI", "TDate": "None", "raw_csv_data": "{'VCode': '60', 'VName': 'RAMANAPUDI', 'TDate': '08/22/21 00:00:00'}", "branch": "None"}}
{"row": 14, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=61: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "61", "VName": "RAMANAPUDI", "TDate": "None", "raw_csv_data": "{'VCode': '61', 'VName': 'RAMANAPUDI', 'TDate': '08/23/21 00:00:00'}", "branch": "None"}}
{"row": 15, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=62: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "62", "VName": "PAMARU (NTR COLONY)", "TDate": "None", "raw_csv_data": "{'VCode': '62', 'VName': 'PAMARU (NTR COLONY)', 'TDate': '08/25/21 00:00:00'}", "branch": "None"}}
{"row": 16, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=63: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "63", "VName": "GUDLAVALLERU", "TDate": "2009-10-21", "raw_csv_data": "{'VCode': '63', 'VName': 'GUDLAVALLERU', 'TDate': '09/10/21 00:00:00'}", "branch": "None"}}
{"row": 17, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=64: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "64", "VName": "KOWTAVARAM", "TDate": "None", "raw_csv_data": "{'VCode': '64', 'VName': 'KOWTAVARAM', 'TDate': '09/17/21 00:00:00'}", "branch": "None"}}
{"row": 18, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=65: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "65", "VName": "PEDASANAGALLU", "TDate": "None", "raw_csv_data": "{'VCode': '65', 'VName': 'PEDASANAGALLU', 'TDate': '09/22/21 00:00:00'}", "branch": "None"}}
{"row": 19, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=66: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "66", "VName": "KOMARAVOLU", "TDate": "2010-05-21", "raw_csv_data": "{'VCode': '66', 'VName': 'KOMARAVOLU', 'TDate': '10/05/21 00:00:00'}", "branch": "None"}}
{"row": 20, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=67: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "67", "VName": "BOMMULURU", "TDate": "None", "raw_csv_data": "{'VCode': '67', 'VName': 'BOMMULURU', 'TDate': '12/15/21 00:00:00'}", "branch": "None"}}
{"row": 21, "error": "NOT NULL constraint failed: companies_village.VName", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.VName\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.VName\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=68: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "68", "VName": "None", "TDate": "None", "raw_csv_data": "{'VCode': '68', 'VName': '', 'TDate': '03/21/22 00:00:00'}", "branch": "None"}}
{"row": 22, "error": "NOT NULL constraint failed: companies_village.VName", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.VName\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.VName\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=69: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "69", "VName": "None", "TDate": "None", "raw_csv_data": "{'VCode': '69', 'VName': '', 'TDate': '03/21/22 00:00:00'}", "branch": "None"}}
{"row": 23, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=70: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "70", "VName": "PEDAVIRIVADA", "TDate": "2004-09-22", "raw_csv_data": "{'VCode': '70', 'VName': 'PEDAVIRIVADA', 'TDate': '04/09/22 00:00:00'}", "branch": "None"}}
{"row": 24, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=71: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "71", "VName": "PENJENDRA", "TDate": "None", "raw_csv_data": "{'VCode': '71', 'VName': 'PENJENDRA', 'TDate': '04/25/22 00:00:00'}", "branch": "None"}}
{"row": 25, "error": "NOT NULL constraint failed: companies_village.VName", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.VName\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.VName\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=72: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "72", "VName": "None", "TDate": "None", "raw_csv_data": "{'VCode': '72', 'VName': '', 'TDate': '04/18/22 00:00:00'}", "branch": "None"}}
{"row": 26, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=73: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "73", "VName": "MANTADA", "TDate": "None", "raw_csv_data": "{'VCode': '73', 'VName': 'MANTADA', 'TDate': '04/18/22 00:00:00'}", "branch": "None"}}
{"row": 27, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=74: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "74", "VName": "KONDIPARRU", "TDate": "None", "raw_csv_data": "{'VCode': '74', 'VName': 'KONDIPARRU', 'TDate': '05/25/22 00:00:00'}", "branch": "None"}}
{"row": 28, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=75: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "75", "VName": "CHIRICHINTALA", "TDate": "None", "raw_csv_data": "{'VCode': '75', 'VName': 'CHIRICHINTALA', 'TDate': '05/25/22 00:00:00'}", "branch": "None"}}
{"row": 29, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=76: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "76", "VName": "MOTURU", "TDate": "None", "raw_csv_data": "{'VCode': '76', 'VName': 'MOTURU', 'TDate': '05/30/22 00:00:00'}", "branch": "None"}}
{"row": 30, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=77: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "77", "VName": "KANCHARIAVANIPURAM", "TDate": "None", "raw_csv_data": "{'VCode': '77', 'VName': 'KANCHARIAVANIPURAM', 'TDate': '06/14/22 00:00:00'}", "branch": "None"}}
{"row": 31, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=78: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "78", "VName": "NALLAGUNTA", "TDate": "2009-02-22", "raw_csv_data": "{'VCode': '78', 'VName': 'NALLAGUNTA', 'TDate': '09/02/22 00:00:00'}", "branch": "None"}}
{"row": 32, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=79: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "79", "VName": "KANCHARLAVANI PURAM  B", "TDate": "None", "raw_csv_data": "{'VCode': '79', 'VName': 'KANCHARLAVANI PURAM  B', 'TDate': '10/29/22 00:00:00'}", "branch": "None"}}
{"row": 33, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=80: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "80", "VName": "MOTURU-B", "TDate": "2011-07-22", "raw_csv_data": "{'VCode': '80', 'VName': 'MOTURU-B', 'TDate': '11/07/22 00:00:00'}", "branch": "None"}}
{"row": 34, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=81: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "81", "VName": "MOTURU", "TDate": "None", "raw_csv_data": "{'VCode': '81', 'VName': 'MOTURU ', 'TDate': '11/19/22 00:00:00'}", "branch": "None"}}
{"row": 35, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=82: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "82", "VName": "KVPURAM C", "TDate": "None", "raw_csv_data": "{'VCode': '82', 'VName': 'KVPURAM C', 'TDate': '05/25/23 00:00:00'}", "branch": "None"}}
{"row": 36, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=83: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "83", "VName": "KORNIPADU", "TDate": "2008-04-23", "raw_csv_data": "{'VCode': '83', 'VName': 'KORNIPADU', 'TDate': '08/04/23 00:00:00'}", "branch": "None"}}
{"row": 37, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=84: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "84", "VName": "DONDAPADU", "TDate": "2009-02-23", "raw_csv_data": "{'VCode': '84', 'VName': 'DONDAPADU', 'TDate': '09/02/23 00:00:00'}", "branch": "None"}}
{"row": 38, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=85: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "85", "VName": "KORNIPADU", "TDate": "2009-08-23", "raw_csv_data": "{'VCode': '85', 'VName': 'KORNIPADU', 'TDate': '09/08/23 00:00:00'}", "branch": "None"}}
{"row": 39, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=86: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "86", "VName": "GANNAVARAM B", "TDate": "2001-11-24", "raw_csv_data": "{'VCode': '86', 'VName': 'GANNAVARAM B', 'TDate': '01/11/24 00:00:00'}", "branch": "None"}}
{"row": 40, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=87: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "87", "VName": "TATTIVARRU", "TDate": "None", "raw_csv_data": "{'VCode': '87', 'VName': 'TATTIVARRU', 'TDate': '06/17/24 00:00:00'}", "branch": "None"}}
{"row": 41, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=88: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "88", "VName": "TATTIVARRU", "TDate": "None", "raw_csv_data": "{'VCode': '88', 'VName': 'TATTIVARRU', 'TDate': '06/24/24 00:00:00'}", "branch": "None"}}
{"row": 42, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=89: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "89", "VName": "THAKKELLA PADU", "TDate": "None", "raw_csv_data": "{'VCode': '89', 'VName': 'THAKKELLA PADU', 'TDate': '12/28/24 00:00:00'}", "branch": "None"}}
{"row": 43, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=90: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "90", "VName": "SURAYA VANI PALEAM", "TDate": "None", "raw_csv_data": "{'VCode': '90', 'VName': 'SURAYA VANI PALEAM', 'TDate': '01/24/25 00:00:00'}", "branch": "None"}}
{"row": 44, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=91: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "91", "VName": "thummalapalli", "TDate": "2002-08-25", "raw_csv_data": "{'VCode': '91', 'VName': 'thummalapalli', 'TDate': '02/08/25 00:00:00'}", "branch": "None"}}
{"row": 45, "error": "NOT NULL constraint failed: companies_village.branch_id", "trace": "Traceback (most recent call last):\n  File \"C:\\Users\\pulla\\AppData\\Roaming\\Python\\Python312\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\sml81\\import_csvs_to_models.py\", line 627, in import_one_file\n    obj.save()\ndjango.db.utils.IntegrityError: NOT NULL constraint failed: companies_village.branch_id\n", "fk_logs": ["[FK] Could not create placeholder Branch for value=92: NOT NULL constraint failed: companies_branch.company_id"], "data": {"VCode": "92", "VName": "CIRICHINTALA", "TDate": "2004-01-25", "raw_csv_data": "{'VCode': '92', 'VName': 'CIRICHINTALA', 'TDate': '04/01/25 00:00:00'}", "branch": "None"}}
